TASK:
  CACHE_DIR: '/data/zixian_z/huggingface'

MODEL:
  NAME: "meta-llama/Meta-Llama-3-8B-Instruct"

DATA:
  NAME: 'Reid996/big_clone_bench'

OUTPUT:
  PROCESSED_PATH: '/home/zixian_z/PycharmProjects/LLM_Code_Clone_Validation/output/llama8b/BCB/output.csv'
  BASE_PATH: '/home/zixian_z/PycharmProjects/LLM_Code_Clone_Validation/output'