
MODEL:
  NAME: "meta-llama/Meta-Llama-3-8B-Instruct"

DATA:
  NAME: 'Reid996/big_clone_bench'

OUTPUT:
  PROCESSED_PATH: '/home/zixian/PycharmProjects/LLM_Code_Clone_Validation/output/meta-llama/Meta-Llama-3-8B-Instruct/Reid996/big_clone_bench/zero_shot/output.csv'
  BASE_PATH: '/home/zixian/PycharmProjects/LLM_Code_Clone_Validation/output'