TASK:
  CACHE_DIR: '/data/zixian_z/huggingface'

MODEL:
  NAME: "codellama/CodeLlama-7b-Instruct-hf"

PROMPT:
  NAME: 'zero_shot'

DATA:
  NAME: 'Reid996/OJClone_code_clone_unbalanced'

OUTPUT:
  BASE_PATH: '/home/zixian_z/PycharmProjects/LLM_Code_Clone_Validation/output'